name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures history is checked out

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Increment Patch Version
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        npm version patch -m "ci: Increment version to %s"
        git push
