name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures history is checked out

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './roomerang.client/package-lock.json'

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Increment Patch Version
      working-directory: ./roomerang.client
      run: |
        npm version patch -m "ci: Increment version to %s" --no-git-tag-version

    - name: Push changes
      run: |
        git add roomerang.client/package.json roomerang.client/package-lock.json
        git commit -m "ci: Increment version to $(node -p -e "require('./roomerang.client/package.json').version")"
        git tag -a "v$(node -p -e "require('./roomerang.client/package.json').version")" -m "ci: Tag version $(node -p -e "require('./roomerang.client/package.json').version")"
        git push --follow-tags
      env:
        GIT_COMMITTER_NAME: github-actions
        GIT_COMMITTER_EMAIL: github-actions@github.com
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com

    - name: Trigger Deploy
      env:
        TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token $TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/alsorokin/roomerang/actions/workflows/static/dispatches \
        -d '{"ref":"master"}'